name: Lint

on:
  pull_request:
    branches: production

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel workflow action
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Lint Fix
        run: pnpm lint:fix
